sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
  - '6'
before_script:
  - npm prune
script:
  - npm test
  - npm run example
  - npm run example-scoped
  - npm run example-standard
after_success:
  - npm run coveralls
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
