language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '8'
script:
  - npm test
  - npm run build
  - npm run example
  - npm run example-scoped
  - npm run example-standard
after_success:
  - npm run coveralls
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
